let a=document.getElementById("input");
let c=document.getElementById("box");
let d=document.getElementById("form");
d.addEventListener("submit",(e)=>{
    e.preventDefault();
    let b=document.getElementById("input").value;
    let div=document.createElement("div");
    div.style.margin="7px";
    div.style.height="115px";
    div.style.width="115px";
    div.textContent=b;
    div.style.backgroundColor="pink";
    div.style.border="2px solid white";
    div.style.borderRadius="11px";
    div.style.textAlign="center";
    div.style.display="flex";
    div.style.alignItems="center";
    div.style.justifyContent="center";
    div.style.overflow="auto";
    div.style.wordBreak="break-word";
    div.classList.add("task");
    div.style.setProperty('scrollbar-width', 'none'); 
    c.appendChild(div);
    a.value="";
});